In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import matplotlib.pyplot as plots

In [2]:
! pip install efficient-apriori

Collecting efficient-apriori
  Downloading efficient_apriori-1.1.1-py3-none-any.whl (14 kB)
Installing collected packages: efficient-apriori
Successfully installed efficient-apriori-1.1.1

In [3]:
from efficient_apriori import apriori

transactions = [('eggs', 'bacon', 'soup'),
                ('eggs', 'bacon', 'apple'),
                ('soup', 'bacon', 'banana')]

print(type(transactions))
itemsets, rules = apriori(transactions, min_support=0.5,  min_confidence=1)
print(rules)

<class 'list'>
[{eggs} -> {bacon}, {soup} -> {bacon}]

In [4]:
from efficient_apriori import apriori

transactions = [('jam', 'bread', 'sugar'),
                ('sugar', 'bacon', 'apple'),
                ('soup', 'bacon', 'banana'),
                ('jam', 'bread', ' apple')]

itemsets, rules = apriori(transactions, min_support=0.2,  min_confidence=1)


rules_rhs = filter(lambda rule: len(rule.lhs) == 2 and len(rule.rhs) == 1, rules)

for rule in sorted(rules_rhs, key=lambda rule: rule.lift):
  print(rule)

{jam, sugar} -> {bread} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{bread, sugar} -> {jam} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{apple, sugar} -> {bacon} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{apple, bacon} -> {sugar} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{banana, soup} -> {bacon} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{ apple, jam} -> {bread} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{ apple, bread} -> {jam} (conf: 1.000, supp: 0.250, lift: 2.000, conv: 500000000.000)
{bacon, sugar} -> {apple} (conf: 1.000, supp: 0.250, lift: 4.000, conv: 750000000.000)
{bacon, soup} -> {banana} (conf: 1.000, supp: 0.250, lift: 4.000, conv: 750000000.000)
{bacon, banana} -> {soup} (conf: 1.000, supp: 0.250, lift: 4.000, conv: 750000000.000)

In [5]:
import pandas

df = pandas.read_csv('https://raw.githubusercontent.com/toshihiroryuu/Dataset-test/main/store_data.csv')

df.head(5)

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
def data_generator(filename):

    def data_gen():
        with open(filename) as file:
            for line in file:
                yield tuple(k.strip() for k in line.split(','))      

    return data_gen

In [12]:
transactions = data_generator('D:\Dataset-test\store_data.csv')
itemsets, rules = apriori(transactions, min_support=0.01, min_confidence=0.5)
rules

[{ground beef, milk} -> {mineral water},
 {eggs, ground beef} -> {mineral water}]

In [14]:
itemsets

{1: {('frozen smoothie',): 475,
  ('vegetables mix',): 193,
  ('tomato juice',): 228,
  ('mineral water',): 1788,
  ('salmon',): 319,
  ('energy drink',): 200,
  ('low fat yogurt',): 574,
  ('honey',): 356,
  ('olive oil',): 494,
  ('shrimp',): 536,
  ('almonds',): 153,
  ('avocado',): 250,
  ('yams',): 86,
  ('green tea',): 991,
  ('cottage cheese',): 239,
  ('meatballs',): 157,
  ('burgers',): 654,
  ('eggs',): 1348,
  ('turkey',): 469,
  ('energy bar',): 203,
  ('whole wheat rice',): 439,
  ('milk',): 972,
  ('whole wheat pasta',): 221,
  ('french fries',): 1282,
  ('light cream',): 117,
  ('soup',): 379,
  ('frozen vegetables',): 715,
  ('spaghetti',): 1306,
  ('cookies',): 603,
  ('cooking oil',): 383,
  ('champagne',): 351,
  ('chocolate',): 1229,
  ('oil',): 173,
  ('chicken',): 450,
  ('fresh tuna',): 167,
  ('extra dark chocolate',): 90,
  ('tomatoes',): 513,
  ('black tea',): 107,
  ('protein bar',): 139,
  ('red wine',): 211,
  ('pepper',): 199,
  ('pasta',): 118,
  ('rice',): 141,
  ('pancakes',): 713,
  ('body spray',): 86,
  ('ham',): 199,
  ('white wine',): 124,
  ('grated cheese',): 393,
  ('fresh bread',): 323,
  ('parmesan cheese',): 149,
  ('escalope',): 595,
  ('ground beef',): 737,
  ('herb & pepper',): 371,
  ('tomato sauce',): 106,
  ('magazines',): 82,
  ('strawberries',): 160,
  ('cake',): 608,
  ('hot dogs',): 243,
  ('brownies',): 253,
  ('cereals',): 193,
  ('muffins',): 181,
  ('light mayo',): 204,
  ('gums',): 101,
  ('cider',): 79,
  ('yogurt cake',): 205,
  ('mint',): 131,
  ('butter',): 226,
  ('french wine',): 169,
  ('barbecue sauce',): 81,
  ('carrots',): 115,
  ('mushroom cream sauce',): 143,
  ('nonfat milk',): 78,
  ('eggplant',): 99,
  ('fromage blanc',): 102,
  ('melons',): 90},
 2: {('avocado', 'mineral water'): 87,
  ('frozen smoothie', 'green tea'): 84,
  ('frozen smoothie', 'mineral water'): 152,
  ('green tea', 'mineral water'): 233,
  ('green tea', 'shrimp'): 86,
  ('honey', 'mineral water'): 113,
  ('low fat yogurt', 'mineral water'): 180,
  ('mineral water', 'olive oil'): 207,
  ('mineral water', 'salmon'): 128,
  ('mineral water', 'shrimp'): 177,
  ('burgers', 'eggs'): 216,
  ('green tea', 'milk'): 132,
  ('milk', 'mineral water'): 360,
  ('milk', 'whole wheat rice'): 89,
  ('mineral water', 'whole wheat rice'): 151,
  ('frozen vegetables', 'green tea'): 108,
  ('frozen vegetables', 'spaghetti'): 209,
  ('green tea', 'spaghetti'): 199,
  ('burgers', 'mineral water'): 183,
  ('burgers', 'turkey'): 80,
  ('cooking oil', 'eggs'): 88,
  ('cooking oil', 'mineral water'): 151,
  ('eggs', 'mineral water'): 382,
  ('eggs', 'turkey'): 146,
  ('mineral water', 'turkey'): 144,
  ('chicken', 'chocolate'): 110,
  ('chocolate', 'cooking oil'): 102,
  ('chocolate', 'low fat yogurt'): 111,
  ('chocolate', 'shrimp'): 135,
  ('chicken', 'eggs'): 108,
  ('chicken', 'mineral water'): 171,
  ('chicken', 'spaghetti'): 129,
  ('eggs', 'spaghetti'): 274,
  ('eggs', 'tomatoes'): 92,
  ('mineral water', 'spaghetti'): 448,
  ('mineral water', 'tomatoes'): 183,
  ('salmon', 'spaghetti'): 101,
  ('spaghetti', 'tomatoes'): 157,
  ('spaghetti', 'turkey'): 124,
  ('french fries', 'milk'): 178,
  ('chocolate', 'eggs'): 249,
  ('eggs', 'shrimp'): 106,
  ('green tea', 'pancakes'): 123,
  ('mineral water', 'pancakes'): 253,
  ('pancakes', 'spaghetti'): 189,
  ('milk', 'soup'): 114,
  ('milk', 'spaghetti'): 266,
  ('soup', 'spaghetti'): 107,
  ('escalope', 'mineral water'): 128,
  ('escalope', 'spaghetti'): 105,
  ('frozen smoothie', 'milk'): 107,
  ('frozen smoothie', 'spaghetti'): 117,
  ('ground beef', 'milk'): 165,
  ('ground beef', 'mineral water'): 307,
  ('ground beef', 'spaghetti'): 294,
  ('chicken', 'french fries'): 83,
  ('chocolate', 'french fries'): 258,
  ('chocolate', 'mineral water'): 395,
  ('eggs', 'french fries'): 273,
  ('french fries', 'mineral water'): 253,
  ('frozen vegetables', 'mineral water'): 268,
  ('french fries', 'turkey'): 80,
  ('chocolate', 'frozen vegetables'): 172,
  ('mineral water', 'red wine'): 82,
  ('cake', 'mineral water'): 206,
  ('honey', 'spaghetti'): 89,
  ('spaghetti', 'whole wheat rice'): 106,
  ('french fries', 'green tea'): 214,
  ('french fries', 'pancakes'): 151,
  ('cereals', 'mineral water'): 77,
  ('burgers', 'green tea'): 131,
  ('chocolate', 'green tea'): 176,
  ('chocolate', 'spaghetti'): 294,
  ('escalope', 'french fries'): 123,
  ('chocolate', 'ground beef'): 173,
  ('chocolate', 'milk'): 241,
  ('chocolate', 'olive oil'): 123,
  ('chocolate', 'soup'): 76,
  ('chocolate', 'tomatoes'): 105,
  ('chocolate', 'turkey'): 85,
  ('frozen vegetables', 'ground beef'): 127,
  ('frozen vegetables', 'milk'): 177,
  ('frozen vegetables', 'olive oil'): 85,
  ('frozen vegetables', 'tomatoes'): 121,
  ('ground beef', 'olive oil'): 106,
  ('ground beef', 'tomatoes'): 88,
  ('milk', 'olive oil'): 128,
  ('milk', 'tomatoes'): 105,
  ('milk', 'turkey'): 85,
  ('mineral water', 'soup'): 173,
  ('olive oil', 'spaghetti'): 172,
  ('cookies', 'eggs'): 79,
  ('chicken', 'green tea'): 89,
  ('green tea', 'turkey'): 89,
  ('ground beef', 'herb & pepper'): 120,
  ('herb & pepper', 'mineral water'): 128,
  ('grated cheese', 'ground beef'): 85,
  ('grated cheese', 'mineral water'): 131,
  ('grated cheese', 'spaghetti'): 124,
  ('cake', 'eggs'): 143,
  ('cake', 'french fries'): 134,
  ('burgers', 'french fries'): 165,
  ('burgers', 'milk'): 134,
  ('burgers', 'spaghetti'): 161,
  ('french fries', 'spaghetti'): 207,
  ('eggs', 'herb & pepper'): 94,
  ('chocolate', 'frozen smoothie'): 112,
  ('french fries', 'low fat yogurt'): 100,
  ('eggs', 'olive oil'): 90,
  ('herb & pepper', 'spaghetti'): 122,
  ('shrimp', 'spaghetti'): 159,
  ('cookies', 'french fries'): 100,
  ('cookies', 'green tea'): 90,
  ('eggs', 'green tea'): 191,
  ('green tea', 'ground beef'): 111,
  ('burgers', 'chocolate'): 128,
  ('burgers', 'ground beef'): 90,
  ('eggs', 'ground beef'): 150,
  ('eggs', 'milk'): 231,
  ('milk', 'shrimp'): 132,
  ('champagne', 'chocolate'): 87,
  ('chocolate', 'escalope'): 132,
  ('fresh bread', 'mineral water'): 100,
  ('eggs', 'low fat yogurt'): 126,
  ('eggs', 'pancakes'): 163,
  ('french fries', 'grated cheese'): 78,
  ('burgers', 'frozen vegetables'): 79,
  ('burgers', 'pancakes'): 79,
  ('chocolate', 'pancakes'): 149,
  ('eggs', 'frozen vegetables'): 163,
  ('french fries', 'frozen vegetables'): 143,
  ('frozen vegetables', 'low fat yogurt'): 76,
  ('frozen vegetables', 'pancakes'): 101,
  ('frozen vegetables', 'shrimp'): 125,
  ('low fat yogurt', 'milk'): 99,
  ('low fat yogurt', 'spaghetti'): 114,
  ('milk', 'pancakes'): 124,
  ('pancakes', 'shrimp'): 79,
  ('cake', 'spaghetti'): 136,
  ('french fries', 'tomatoes'): 90,
  ('eggs', 'frozen smoothie'): 83,
  ('cake', 'chocolate'): 102,
  ('cake', 'milk'): 100,
  ('cooking oil', 'milk'): 86,
  ('cooking oil', 'spaghetti'): 119,
  ('red wine', 'spaghetti'): 77,
  ('ground beef', 'shrimp'): 86,
  ('chocolate', 'whole wheat rice'): 90,
  ('eggs', 'whole wheat rice'): 82,
  ('olive oil', 'pancakes'): 81,
  ('french fries', 'frozen smoothie'): 109,
  ('shrimp', 'tomatoes'): 84,
  ('ground beef', 'pancakes'): 109,
  ('eggs', 'escalope'): 83,
  ('chocolate', 'grated cheese'): 82,
  ('burgers', 'cake'): 86,
  ('cake', 'green tea'): 106,
  ('chocolate', 'salmon'): 80,
  ('chocolate', 'cookies'): 78,
  ('french fries', 'ground beef'): 104,
  ('french fries', 'whole wheat rice'): 79,
  ('green tea', 'tomatoes'): 92,
  ('cake', 'frozen vegetables'): 77,
  ('cake', 'pancakes'): 89,
  ('chicken', 'milk'): 111},
 3: {('eggs', 'mineral water', 'spaghetti'): 107,
  ('mineral water', 'pancakes', 'spaghetti'): 86,
  ('ground beef', 'milk', 'mineral water'): 83,
  ('ground beef', 'mineral water', 'spaghetti'): 128,
  ('milk', 'mineral water', 'spaghetti'): 118,
  ('chocolate', 'eggs', 'mineral water'): 101,
  ('frozen vegetables', 'mineral water', 'spaghetti'): 90,
  ('chocolate', 'ground beef', 'mineral water'): 82,
  ('chocolate', 'milk', 'mineral water'): 105,
  ('chocolate', 'milk', 'spaghetti'): 82,
  ('chocolate', 'mineral water', 'spaghetti'): 119,
  ('frozen vegetables', 'milk', 'mineral water'): 83,
  ('mineral water', 'olive oil', 'spaghetti'): 77,
  ('chocolate', 'eggs', 'spaghetti'): 79,
  ('eggs', 'ground beef', 'mineral water'): 76,
  ('eggs', 'milk', 'mineral water'): 98,
  ('french fries', 'mineral water', 'spaghetti'): 76}}

In [16]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

itemsets, rules = apriori(dataset, min_support=0.5,  min_confidence=1)
print(rules)

[{Eggs} -> {Kidney Beans}, {Onion} -> {Eggs}, {Milk} -> {Kidney Beans}, {Onion} -> {Kidney Beans}, {Yogurt} -> {Kidney Beans}, {Kidney Beans, Onion} -> {Eggs}, {Eggs, Onion} -> {Kidney Beans}, {Onion} -> {Eggs, Kidney Beans}]

In [17]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

type(dataset)

list

In [18]:
! pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.18.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: numpy>=1.16.2 in c:\users\athul\anaconda3\lib\site-packages (from mlxtend) (1.19.3)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\athul\appdata\roaming\python\python38\site-packages (from mlxtend) (0.23.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\athul\appdata\roaming\python\python38\site-packages (from mlxtend) (1.0.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\athul\anaconda3\lib\site-packages (from mlxtend) (3.3.2)
Requirement already satisfied: setuptools in c:\users\athul\anaconda3\lib\site-packages (from mlxtend) (56.0.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\athul\anaconda3\lib\site-packages (from mlxtend) (1.4.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\athul\appdata\roaming\python\python38\site-packages (from mlxtend) (1.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (7.0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\athul\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: six in c:\users\athul\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\athul\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\athul\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.18.0

In [19]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

In [20]:
from mlxtend.frequent_patterns import apriori

apriori(df, min_support=0.6)

    support   itemsets
0       0.8        (3)
1       1.0        (5)
2       0.6        (6)
3       0.6        (8)
4       0.6       (10)
5       0.8     (3, 5)
6       0.6     (8, 3)
7       0.6     (5, 6)
8       0.6     (8, 5)
9       0.6    (10, 5)
10      0.6  (8, 3, 5)

In [21]:
apriori(df, min_support=0.6, use_colnames=True)

    support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Eggs, Kidney Beans)
6       0.6                (Onion, Eggs)
7       0.6         (Milk, Kidney Beans)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Kidney Beans, Yogurt)
10      0.6  (Onion, Eggs, Kidney Beans)

In [22]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

    support                     itemsets  length
0       0.8                       (Eggs)       1
1       1.0               (Kidney Beans)       1
2       0.6                       (Milk)       1
3       0.6                      (Onion)       1
4       0.6                     (Yogurt)       1
5       0.8         (Eggs, Kidney Beans)       2
6       0.6                (Onion, Eggs)       2
7       0.6         (Milk, Kidney Beans)       2
8       0.6        (Onion, Kidney Beans)       2
9       0.6       (Kidney Beans, Yogurt)       2
10      0.6  (Onion, Eggs, Kidney Beans)       3

In [23]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) & (frequent_itemsets['support'] >= 0.8) ]

   support              itemsets  length
5      0.8  (Eggs, Kidney Beans)       2

In [24]:
frequent_itemsets[ frequent_itemsets['itemsets'] == {'Onion', 'Eggs'} ]

   support       itemsets  length
6      0.6  (Onion, Eggs)       2